name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          apt update
          sudo dpkg --add-architecture arm64
          apt install -y qemu qemu-user-static wget libfuse2:arm64
          uname -a
          wget https://cloud.john-livingston.fr/s/jKc7besKdzWm6pf/download/bash-4.4.20-aarch64.2.AppImage
          chmod +x bash-4.4.20-aarch64.2.AppImage
          ./bash-4.4.20-aarch64.2.AppImage -c 'env'
