name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            sudo apt update
            sudo apt install wget
            uname -a
            wget https://cloud.john-livingston.fr/s/jKc7besKdzWm6pf/download/bash-4.4.20-aarch64.2.AppImage
            chmod +x bash-4.4.20-aarch64.2.AppImage
            ./bash-4.4.20-aarch64.2.AppImage -c 'env'
